apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  ports:
    - port: {{ .Values.mongodb.service.port }}
      targetPort: 27017
  selector:
    app: mongodb
  type: {{ .Values.mongodb.service.type }}