apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.mongodb.dbName }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.mongodb.dbName }}
  template:
    metadata:
      labels:
        app: {{ .Values.mongodb.dbName }}
    spec:
      containers:
        - name: mongo
          image: "{{ .Values.mongodb.image }}"
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: {{ .Values.mongodb.username }}
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: {{ .Values.mongodb.password }}
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongodb-data
              mountPath: /data/db
      volumes:
        - name: mongodb-data
          persistentVolumeClaim:
            claimName: mongodb-data