apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mongodb.dbName }}
spec:
  ports:
    - port: 27017
      targetPort: {{ .Values.mongodb.servicePort }}
  selector:
    app: {{ .Values.mongodb.dbName }}