apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: app
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: app
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yaml
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: app
    spec:
      containers:
        - env:
            - name: MONGO_DB_NAME
              value: app-desafio10
            - name: MONGO_DB_PASS
              value: s3cr3t!
            - name: MONGO_DB_URI
              value: mongodb://db-server:27017
            - name: MONGO_DB_USER
              value: root
            - name: PORT
              value: "3000"
          image: marcosdecimadepietro/desafio11:latest
          name: educacionit-app
          ports:
            - containerPort: 3000
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
